[build]
  publish = "build/web"
  command = "flutter build web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  SERVICE_ID = "service_m9u64hl"
  TEMPLATE_ID = "template_6tylfoq"
  USER_ID = "Dht4gdG2x81QTQ4ma"
