name: tekkom_web
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1 # Renders SVG (Scalable Vector Graphics) files
  cupertino_icons: ^1.0.6 # Cupertino style icons for iOS design
  google_fonts: ^6.2.1 # Allows the use of fonts from Google Fonts
  animate_do: ^3.3.4 # Used to add animation effects.
  google_maps_flutter: ^2.9.0 # Used to show adress on map.
  http: ^1.2.2 # Used for http requests.

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0 # Linter rules for code quality and consistency

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

