name: tekkom_web
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1 # Renders SVG (Scalable Vector Graphics) files
  cupertino_icons: ^1.0.6 # Cupertino style icons for iOS design
  google_fonts: ^6.2.1 # Allows the use of fonts from Google Fonts
  animate_do: ^3.3.4 # Used to add animation effects.
  google_maps_flutter: ^2.9.0 # Used to show adress on map.
  http: ^1.2.2 # Used for http requests.
  font_awesome_flutter: ^10.7.0 # Used for Icons
  url_launcher: ^6.3.1 # Used for laucnhing url's
  equatable: ^2.0.7 # used to prevent object reference shifts
  carousel_slider: ^5.0.0 # used to slideble uş design's
  provider: ^6.1.2 # Used for state management 
  easy_localization: ^3.0.7 # Simplifies localization and internationalization of the app
  html: ^0.15.5 # Used for http requests.
  flutter_dotenv: ^5.2.1  # Used for loading environment variables from a .env fil
  shared_preferences_web: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0 # Linter rules for code quality and consistency

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/